name: CaveSurveyBTEmulator Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: package
      run: mvn package
    - name: Store war
      uses: actions/upload-artifact@v1
      with:
        name: CaveSurveyBTEmulator.war
        path: target